# Site settings
title: login.gov Playbook
description: >
  The identity principles will help developers and technologists in government agencies build
  usable, secure, and privacy-protecting consumer identity management systems.
baseurl: '/identity-playbook'
url: 'https://pages.18f.gov'

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
  - node_modules

# Addons
gems:
  - octopress-autoprefixer
